# Generated by Django 3.1.5 on 2024-09-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0010_auto_20240928_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='dept',
            new_name='department',
        ),
    ]
