# Generated by Django 3.1.5 on 2024-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0012_auto_20240928_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
