# Generated by Django 3.1.5 on 2024-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0016_auto_20240928_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'staff')], default=1, max_length=50),
        ),
    ]
