# Generated by Django 5.1.1 on 2024-09-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slmsapp", "0018_alter_customuser_id_alter_staff_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="department",
            new_name="dept",
        ),
    ]
