# Generated by Django 3.2.25 on 2024-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0021_auto_20240928_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification',
            field=models.CharField(default=None, max_length=2500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'staff'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
