# Generated by Django 5.0.4 on 2024-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slmsapp', '0023_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(unique=True)),
                ('date', models.CharField(max_length=100)),
                ('pdays', models.IntegerField()),
            ],
        ),
    ]
